@startuml
'https://plantuml.com/class-diagram

class OnyxParallelDeadlineGroup
class ParallelDeadlineGroup
class ParallelCommandGroup

OnyxParallelDeadlineGroup-|> ParallelDeadlineGroup
LoadBalls -|> ParallelCommandGroup
LoadUntilTwoBalls -|> OnyxParallelDeadlineGroup
MoveBallTriggerUntilBallInPlace -|> OnyxParallelDeadlineGroup

class LoadBalls
class LoadUntilTwoBalls
class MoveBallTriggerUntilBallInPlace

@enduml